In [4]:
# 타깃 없는 데이터셋에서 토픽 잡기

In [5]:
!pip install -u pandas


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -u


In [6]:
import pandas
import pyLDAvis
import pyLDAvis.lda_model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation         # 분장에서 토픽을 찾을수 있다.
from sklearn.datasets import fetch_20newsgroups
# 데이터 로드
data = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))
documents = data.data

In [7]:
documents[:1]

['I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.']

### TfidfVectorizer
- max_df= : 단어가 전체 문서의 95% 이상에서 나타나면 해당 단어는 무시해라.(너무 많이 반복되는 단어(너무 too much하게 반복이 많으면 의미가 없다고 봄.))
- min_df= 단어가 최소한 2개의 문서에서 나타나야만 해당 단어가 유지해라.(너무 극소수로 나타나는 단어(너무 적은 수의 단어가 의미가 특별히 없다고 봄.))

In [8]:
tfidfVectorizer = TfidfVectorizer(stop_words='english', max_df=0.95, min_df=2)

In [9]:
tfidf = tfidfVectorizer.fit_transform(documents)
tfidf.toarray()[:1]

array([[0., 0., 0., ..., 0., 0., 0.]])

In [10]:
import numpy as np
np.where(tfidf.toarray()[:1] > 0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 2582,  2918,  4348,  7279,  7618,  7843,  8160,  8308, 11269,
        12709, 12710, 13133, 13725, 13755, 15821, 17670, 18895, 20611,
        20958, 21663, 21665, 22151, 23553, 27879, 29041, 29858, 30936,
        31406, 32237, 32669, 32807, 37946, 38743]))

## 5개로 범주화

In [11]:
latentDirichletAllocation = LatentDirichletAllocation(n_components=5, n_jobs=-1)     # n_components=5 : 5개로 범주화하라는 코드

In [12]:
latentDirichletAllocation.fit(tfidf)

LatentDirichletAllocation(n_components=5, n_jobs=-1)

In [13]:
vis = pyLDAvis.lda_model.prepare(latentDirichletAllocation, tfidf, tfidfVectorizer)

In [14]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis)