# quests
- dataset 
- LDA 적용과 LDAvis 적용

In [26]:
import pandas as pd
import pyLDAvis
import pyLDAvis.lda_model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation         # 분장에서 토픽을 찾을수 있다.
from sklearn.datasets import fetch_20newsgroups

## 데이터 로드(자료 입력)

In [29]:
TDM_s120 = pd.read_csv("https://bit.ly/seoul-120-text-csv")
TDM_s120_content = TDM_s120['내용']
TDM_s120_content[:3]

0    아빠 육아휴직 장려금   업무개요  남성근로자의 육아휴직을 장려하고 양육에 따른 경...
1    서울산업진흥원 서울메이드란 서울의 감성을 담은 다양하고 새로운 경험을 제공하기 위해...
2    강북구 정비중  업무개요  투명 폐트병을 교환보상하므로 수거율을 높이고 폐기물을 감...
Name: 내용, dtype: object

## 자연어 처리

In [30]:
stopwords = []

In [31]:
# 토크나이징 함수 정의
from konlpy.tag import Okt
okt = Okt()

def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=stopwords):
    return [
        word for word, tag in okt.pos(
            raw, 
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword

    ]

In [32]:
# tokenizing
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfvectorizer = TfidfVectorizer(tokenizer=tokenizer)

### TfidfVectorizer

In [34]:
tfidf = tfidfVectorizer.fit_transform(TDM_s120_content)
tfidf.toarray()[:1]

array([[0., 0., 0., ..., 0., 0., 0.]])

In [36]:
import numpy as np
np.where(tfidf.toarray()[:1] > 0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([  372,   445,  7289,  8917, 10351, 11148, 12913, 15653, 18851,
        23031, 23749, 25079, 25689, 27342, 27343, 27346, 27347, 30624,
        31756, 33558, 34940]))

## 3개로 범주화

In [49]:
latentDirichletAllocation3 = LatentDirichletAllocation(n_components=3, n_jobs=-1)    # n_components=5 : 3개로 범주화하라는 코드

In [43]:
latentDirichletAllocation3.fit(tfidf)

LatentDirichletAllocation(n_components=3, n_jobs=-1)

In [46]:
vis = pyLDAvis.lda_model.prepare(latentDirichletAllocation3, tfidf, tfidfVectorizer)

In [47]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis)

## 5개로 범주화

In [52]:
latentDirichletAllocation5 = LatentDirichletAllocation(n_components=5, n_jobs=-1)    # n_components=5 : 5개로 범주화하라는 코드

In [53]:
latentDirichletAllocation5.fit(tfidf)

LatentDirichletAllocation(n_components=5, n_jobs=-1)

In [54]:
vis = pyLDAvis.lda_model.prepare(latentDirichletAllocation5, tfidf, tfidfVectorizer)

In [55]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis)

## 7개로 범주화

In [56]:
latentDirichletAllocation7 = LatentDirichletAllocation(n_components=7, n_jobs=-1)    # n_components=5 : 3개로 범주화하라는 코드

In [57]:
latentDirichletAllocation7.fit(tfidf)

LatentDirichletAllocation(n_components=7, n_jobs=-1)

In [58]:
vis = pyLDAvis.lda_model.prepare(latentDirichletAllocation7, tfidf, tfidfVectorizer)

In [59]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis)